### ISSUE TITLE
Issue loading posts

### ISSUE THREAD

**Issue by nickpish** [Robbertdk/wordpress-ajax-filter-posts#2]
First off, thank you for creating this plugin- it looks to do exactly what I need for a current project. I'm experiencing an issue with the posts not loading, however, when clicking on filters. On my template page, using the shortcode, I can see the filters and posts rendered on the page, but when I click on one of the terms to filter posts, it just hangs with the animation and I see in the console: 

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)
ajax-filter-posts.js?ver=4.8:193 
(index):1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onload (ajax-filter-posts.js?ver=4.8:200)`

Do you know what might be happening here?

**Comment by Robbertdk** [comment]
Hi Nick, 

Thank you for using this plugin.
You're the first person that I don't know, that uses one of my small open source contributions! 🎉

I've installed the plugin on a fresh WordPress install and found a bug; probably the same bug that you encountered. Fixed the problem and pushed it to this repo: 65209ab. Can you check if that fixed your problem?

**Comment by nickpish** [comment]
Hi Robbert,

On a Google search for AJAX post filter plugin, your project comes right up!

I just updated my code, and the issue still seems to be occurring. If it's helpful, I push it to  a test WordPress environment I've set up so you can see what's happening?

Thanks for the prompt response! I'd love to use your plugin over a bloated alternative :)

**Comment by Robbertdk** [comment]
Ah, unfortunately.
Yes please, that would be helpful. Although I'll be only able to see what you sent to the server, not what the specific error is.

Some other data that would be useful to solve this:
- Can you see a possible error in the php error log?
- What php version do you use?

**Comment by nickpish** [comment]
Ah, I just turned debug on and I'm seeing the following PHP error:

`Notice: Use of undefined constant ICL_LANGUAGE_CODE - assumed 'ICL_LANGUAGE_CODE' in C:\wamp64\www\wp-dev\wp-content\plugins\ajax-filter-posts\class-ajax-filter-posts.php on line 85`

The same error is thrown for line 86. Can I somehow disable the language option?

**Comment by Robbertdk** [comment]
Ah, the if statement `function_exists('icl_object_id')` above the use of that declaration should skip that code if you don't have WPML installed. That prevented errors here, when WPML not installed. Can you replace the function `function_exists('icl_object_id')`  with `defined('ICL_LANGUAGE_CODE')` to see if that fixes it? You'll find that function, two times in the [class-ajax-filter-posts.php](https://github.com/Robbertdk/wordpress-ajax-filter-posts/blob/master/class-ajax-filter-posts.php) file. On line [89](https://github.com/Robbertdk/wordpress-ajax-filter-posts/blob/master/class-ajax-filter-posts.php#L89) and on line [273](https://github.com/Robbertdk/wordpress-ajax-filter-posts/blob/master/class-ajax-filter-posts.php#L273)

**Comment by Robbertdk** [comment]
Because your error is on the wrong line number, I think you still have the older version of the plugin, before the fix in commit 65209ab.

**Comment by nickpish** [comment]
Ah ok, I thought I had updated the plugin with that commit- I will check, thank you!

**Comment by nickpish** [comment]
Ok, I've got it working! Sorry, I realized I was in fact using the older plugin version. I have a couple modifications I'd like to add for my project, and I'm wondering how difficult they'd be to add? I'm attaching a mockup for reference- first, would it be relatively simple to add the active tags above the search results, with '[x]' buttons to allow quick toggling of the filters? Secondly, how would one go about formatting filter output markup to indent child taxonomy terms under their parent, as in the visual? Thanks for any assistance- I was contemplating using a different plugin, but I'd much rather use your approach!

![wp-ajax-filter-mockup](https://user-images.githubusercontent.com/4361220/28089671-c60f970a-6657-11e7-89e6-a3e97cffb436.png)

**Comment by Robbertdk** [comment]
There are several ways to go:

1. You add the files of the template folder to you your theme in the folder `ajax-filter-posts`. With that you can change the HTML markup of the all the created HTML of this plugin. For example you could add an extra class to the filters if they are child-categories (check if $filter->parent != 0).

You can add your own CSS  in the theme and, if you make a lot of changes to the css, dequeue the CSS from the plugin to prevent loading of a lot of unneeded styles.

You can create your own JavaScript event listeners that listen on changes of the checkbox. When a checkbox is checked you can add that filter as pills above the results and remove it on uncheck. To create the remove button in the pills you can add an eventListener there that triggers an uncheck event on the corresponding filter in the sidemenu.

2. You can create a fork of this plugin and add features of option 1 directly in the plugin.

Now the bug is solved, I'll close this thread. Good luck with your project and feel free to ask more questions!
