### ISSUE TITLE
Post status

### ISSUE THREAD

**Issue by marsaultgaetan** [Robbertdk/wordpress-ajax-filter-posts#26]
Hi, is it possible to add the post_status in query args ?
Thanks for your answer !

**Comment by Robbertdk** [comment]
Hi, thanks for your request. I think this would be a nice addition. Will look into this.

As a quick fix, you can add your own query arguments via the `ajax_filter_posts_query_args` filter hook. See https://github.com/Robbertdk/wordpress-ajax-filter-posts#filters-hooks

**Comment by Robbertdk** [comment]
@marsaultgaetan This issue is revoled in https://github.com/Robbertdk/wordpress-ajax-filter-posts/commit/1f274c084fd5d694b47c137b9bd4822f168c4f38
