### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by Tinougit** [Robbertdk/wordpress-ajax-filter-posts#4]
**UPDATE**
This issue was due to Polylang plugin, after deactivate it, everything worked correctly. I tried Loco Translate and everything seems ok now.

Hi,
I just found your awesome plugin and tried it but there is a JSON parse error when trying to load more or filter my posts.

Here the console log error : 

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onload (ajax-filter-posts.js?ver=4.9.6:200)
```

I changed the line 188 in ajax-filter-posts.js : 
`request.setRequestHeader("Content-Type", "text/plain");`

It seems to be working, but I'm not sure if it's ok and secondly, a load more or filter request now return a 400 Bad Request error:

```
POST http://skald/wp-admin/admin-ajax.php 400 (Bad Request)

getAJAXPosts @ ajax-filter-posts.js?ver=4.9.6:230
handleFilterEvent @ ajax-filter-posts.js?ver=4.9.6:84
(anonymous) @ ajax-filter-posts.js?ver=4.9.6:24
(anonymous) @ ajax-filter-posts.js?ver=4.9.6:264
ajax-filter-posts.js?ver=4.9.6:193

0
```

I don't know if you're still updating this plugin, but is there a way to help me with that ?

Thanks.

**Comment by Robbertdk** [comment]
Hi,

Good to hear the problem is solved. I am on a holiday so I wasn't in the position to reply earlier.
If you find any bugs or have any questions, feel free to post them.
