### ISSUE TITLE
See all terms even if there is no product linked to one of them

### ISSUE THREAD

**Issue by Tinougit** [Robbertdk/wordpress-ajax-filter-posts#5]
Hi,

this is not really an issue but, I wanted to know if it's possible to display all terms even if there is 0 product in one of them.
Currently, if a term is not "linked" with any product, it does not appear in my filter.

Can you tell me if there is a way to do this ? (I couldn't find a hook or something to do this).

Thanks,
Quentin

**Comment by Robbertdk** [comment]
Hi Quentin,

There isn't a hook for this, but feel free to add one!
For each Taxonomy added in the shortcode, Wordpress gets the terms for that taxonomy with [the get_term function.](https://developer.wordpress.org/reference/functions/get_terms/) This function is called [on this line](https://github.com/Robbertdk/wordpress-ajax-filter-posts/blob/b6f7db115deea6aa9f6d352174144b0a6569439e/class-ajax-filter-posts.php#L150)

As you can in the WordPress example on the [get_terms page](https://developer.wordpress.org/reference/functions/get_terms/), you can pass an argument that will show the terms:
```
$terms = get_terms( 'post_tag', array(
    'hide_empty' => false,
) );
```
Feel free to write a filter for the in this plugin and submit a PR

**Comment by Tinougit** [comment]
Hello,

thanks for your reply, I'm not very comfortable with hooks and unfortunately I don't have much time to learn that now so I just passed the hide_empty argument in the get_terms function and it did the job, thanks !

Quentin
